INSERT INTO dbo.customers (id, name, street, city, state, credit_limit)VALUES(1, 'Pedro Daniel', 'Rua Limoeiro', 'Contagem', 'MG', 200000)
INSERT INTO dbo.customers (id, name, street, city, state, credit_limit)VALUES(2, 'Nicolas Diogo Cardoso', 'Acesso Um', 'Porto Alegre', 'RS', 475)
INSERT INTO dbo.customers (id, name, street, city, state, credit_limit)VALUES(3, 'Cecília Olivia Rodrigues', 'Rua Sizuka Usuy', 'Cianorte', 'PR', 3000)
INSERT INTO dbo.customers (id, name, street, city, state, credit_limit)VALUES(4, 'Augusto Fernando Carlos Eduardo Cardoso', 'Rua Baldomiro Koerich', 'Palhoça', 'SC', 1067)
INSERT INTO dbo.customers (id, name, street, city, state, credit_limit)VALUES(5, 'Nicolas Diogo Cardoso', 'Rua Baldomiro Koerich', 'Porto Alegre', 'RS', 465)
INSERT INTO dbo.customers (id, name, street, city, state, credit_limit)VALUES(6, 'Sabrina Heloisa Gabriela Barros','Rua Engenheiro Tito Marques Fernandes', 'Porto Alegre', 'RS', 4312)
INSERT INTO dbo.customers (id, name, street, city, state, credit_limit)VALUES(4, 'Joaquim Diego Lorenzo Araújo','Rua Vitorino', 'Novo Hamburgo', 'RS', 234)